[package]
name = "twilight-interactions"
version = "0.1.0"
edition = "2018"
license = "ISC"

[features]
default = ["derive"]
derive = ["twilight-interactions-derive"]
http = ["twilight-http"]

[dependencies]
twilight-model = "0.7"
twilight-interactions-derive = { path = "../twilight-interactions-derive", optional = true }
twilight-http =  { version = "0.7", optional = true }

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]
