[advisories]
vulnerability = "deny"
unmaintained = "warn"
ignore = []

[licenses]
allow = [
    "MIT",
    "ISC",
    "Apache-2.0",
    "Unicode-DFS-2016",  # unicode-ident
]

unlicensed = "deny"
default = "deny"
confidence-threshold = 0.8

[bans]
multiple-versions = "deny"
wildcards = "deny"

[sources]
unknown-registry = "deny"
unknown-git = "deny"

allow-git = [
    "https://github.com/twilight-rs/twilight",
]
